apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-05-30T11:28:31Z"
  generation: 5
  labels:
    app: springpetclinicrest
  name: springpetclinicrest
  namespace: default
  resourceVersion: "13253"
  uid: 1fb00e47-8876-4b56-acba-dac8dcda2d13
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springpetclinicrest
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springpetclinicrest
    spec:
      containers:
        - image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
          imagePullPolicy: IfNotPresent
          name: spring-petclinic-rest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
    - lastTransitionTime: "2025-05-30T11:35:32Z"
      lastUpdateTime: "2025-05-30T11:35:32Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-05-30T11:28:31Z"
      lastUpdateTime: "2025-05-30T11:41:36Z"
      message: ReplicaSet "springpetclinicrest-7bd6ffcfc9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 5
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
